#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

input=`cat`

echo "ARG1: $1"
echo $input

machineName=$(echo $input | jq -r '.source.machineName')

machineConfigDir = "~/.docker/machine/machines/$machineName"
mkdir -p $machineConfigDir

echo $input | jq -r '.source.ca_pem' >$machineConfigDir/ca.pem
echo $input | jq -r '.source.cert_pem' >$machineConfigDir/cert.pem
echo $input | jq -r '.source.config' >$machineConfigDir/config.json
echo $input | jq -r '.source.id_rsa' >$machineConfigDir/id_rsa
echo $input | jq -r '.source.id_rsa_pub' >$machineConfigDir/id_rsa.pub
echo $input | jq -r '.source.key_pem' >$machineConfigDir/key.pem
echo $input | jq -r '.source.server_key_pem' >$machineConfigDir/server_key.pem
echo $input | jq -r '.source.server_pem' >$machineConfigDir/server.pem

docker-machine ls

jq -n "{
  version: {
    ref: \"$BUILD_ID\"
  },
}" >&3
