#!/bin/bash -ex
# vim: set ft=sh

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

set -x +v
input=`cat`

echo $input | jq -r '.source' | json-to-docker-machine

machineName=$(echo $input | jq -r '.source.machine_name')
composeRoot=$1/$(echo $input | jq -r '.source.compose_root')
composeFile=$(echo $input | jq -r '.source.compose_file')

set -v +x

eval `docker-machine env --shell bash $machineName`

docker-compose -f $composeFile down
docker-compose -f $composeFile build
docker-compose -f $composeFile up -d

jq -n "{
  version: {
    ref: \"$BUILD_ID\"
  }
}" >&3
