#!/bin/bash -ex
# vim: set ft=sh

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

set -x +v
input=`cat`

echo $input | jq -r '.source' | json-to-docker-machine

machineName=$(echo $input | jq -r '.source.machine_name')
composeRoot=$1/$(echo $input | jq -r '.source.compose_root')
composeFile=$(echo $input | jq -r '.source.compose_file')
composeProjectName=$(echo $input | jq -r '.source.compose_project_name')

dockerImage=$1/$(echo $input | jq -r '.source.docker_image')
imageDigest=$(jq -r '.[0].RepoDigests[0]' $dockerImage)

set -v +x

echo "Deploying $imageDigest"

export DEPLOYMENT_IMAGE=$imageDigest

eval `docker-machine env --shell bash $machineName`

cd $composeRoot

docker-compose -f $composeFile -p $composeProjectName down
docker-compose -f $composeFile -p $composeProjectName build
docker-compose -f $composeFile -p $composeProjectName up -d

jq -n "{
  version: {
    ref: \"$BUILD_ID\"
  }
}" >&3
